// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN3-EHevnWLMSfLCp2SbLBRlCqA49GpNo',
    appId: '1:35956651481:web:30a78a203147963cf3d5c8',
    messagingSenderId: '35956651481',
    projectId: 'datingapp-fea1f',
    authDomain: 'datingapp-fea1f.firebaseapp.com',
    storageBucket: 'datingapp-fea1f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxxm75G_qK41iCojY8v-HxlluB8-texaw',
    appId: '1:35956651481:android:a24b23cb32f2dd9ff3d5c8',
    messagingSenderId: '35956651481',
    projectId: 'datingapp-fea1f',
    storageBucket: 'datingapp-fea1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCBEWmNROTq4ihXSnckQSre4SyiAMpuFw',
    appId: '1:35956651481:ios:6bce3637734fe578f3d5c8',
    messagingSenderId: '35956651481',
    projectId: 'datingapp-fea1f',
    storageBucket: 'datingapp-fea1f.appspot.com',
    iosBundleId: 'com.example.dattingAppf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCBEWmNROTq4ihXSnckQSre4SyiAMpuFw',
    appId: '1:35956651481:ios:a4c549d111021a96f3d5c8',
    messagingSenderId: '35956651481',
    projectId: 'datingapp-fea1f',
    storageBucket: 'datingapp-fea1f.appspot.com',
    iosBundleId: 'com.example.dattingAppf.RunnerTests',
  );
}
